# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-31 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='flag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
