from django.conf.urls import url, include
from rest_framework import routers
from .views import MessageViewSet, PostViewSet, PostCommentViewSet, NotificationViewSet


# Configuring the router
router = routers.DefaultRouter()
router.register('messages', MessageViewSet)
router.register('posts', PostViewSet)
router.register('postcomments', PostCommentViewSet)
router.register('notifications', NotificationViewSet)


# Attaching the urlconf generated by the rounter to the urlpatterns	
urlpatterns = router.urls


