# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-16 23:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='chatgroup_avatar')),
                ('label', models.SlugField(unique=True)),
                ('members', models.ManyToManyField(blank=True, related_name='is_member', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.SlugField(unique=True)),
                ('chatgroup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chats.ChatGroup')),
                ('online_participants', models.ManyToManyField(blank=True, related_name='globalchat_online_participants', to=settings.AUTH_USER_MODEL)),
                ('saves', models.ManyToManyField(blank=True, related_name='globalchat_saves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocalChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, upload_to='localchat_avatar')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('label', models.SlugField(unique=True)),
                ('chatgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localchat_chatgroup', to='chats.ChatGroup')),
                ('online_participants', models.ManyToManyField(blank=True, related_name='localchat_online', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('saves', models.ManyToManyField(blank=True, related_name='localchat_saves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(blank=True, max_length=200)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile_avatar')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('label', models.SlugField(unique=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='is_following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, upload_to='topic_avatar')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('label', models.SlugField(unique=True)),
                ('arrow_downs', models.ManyToManyField(blank=True, related_name='arrow_downs', to=settings.AUTH_USER_MODEL)),
                ('arrow_ups', models.ManyToManyField(blank=True, related_name='arrow_ups', to=settings.AUTH_USER_MODEL)),
                ('chatgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_chatgroup', to='chats.ChatGroup')),
                ('online_participants', models.ManyToManyField(blank=True, related_name='topic_online', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('saves', models.ManyToManyField(blank=True, related_name='topic_saves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
