# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-26 16:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0002_auto_20180222_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalchat',
            name='saves',
            field=models.ManyToManyField(related_name='globalchat_saves', to=settings.AUTH_USER_MODEL),
        ),
    ]
