# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-26 16:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_globalchat_saves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalchat',
            name='online_participants',
            field=models.ManyToManyField(blank=True, related_name='globalchat_online_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='globalchat',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='globalchat_saves', to=settings.AUTH_USER_MODEL),
        ),
    ]
