from django.conf.urls import url, include
from rest_framework import routers
from . import views
from .views import ChatGroupViewSet, UserViewSet, TopicViewSet, LocalChatViewSet, GlobalChatViewSet, ProfileViewSet


# Configuring the router
router = routers.DefaultRouter()
router.register('chatgroups', ChatGroupViewSet)
router.register('users', UserViewSet)
router.register('topics', TopicViewSet)
router.register('localchats', LocalChatViewSet)
router.register('globalchats', GlobalChatViewSet)
router.register('profiles', ProfileViewSet)

# Attaching the urlconf generated by the rounter to the urlpatterns	
urlpatterns = router.urls


